language: php
php:
  - 5.6
  - 7
  - 7.1
  - nightly

matrix:
  include:
    - php: "hhvm"
      env:
        - NO_COVERAGE=1
        - BZION_HHVM=1
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
 - curl -sS https://getcomposer.org/installer | php

before_script: bash -xe tests/initialize.sh

script:
  - tests/runTests.sh
  - vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

cache:
  directories:
  - vendor

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
