language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
    include:
        - php: "hhvm"
          env:
            - NO_COVERAGE=1
            - BZION_HHVM=1
    allow_failures:
        - php: hhvm
    fast_finish: true

install:
 - curl -sS https://getcomposer.org/installer | php

before_script: bash -xe tests/initialize.sh

script: tests/runTests.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

cache:
  directories:
  - vendor

notifications:
  webhooks:
    - http://helit.tech:8093/+sujevo-dev/showSuccessfulBuildMessages=always
