index:
    path:   /
    defaults: { _controller: 'Home', _action: 'show' }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    defaults: { _defaultHandler: true }

admin_list:
    path:     /admins
    defaults: { _controller: 'Admin', _action: 'list' }

admin_wipe:
    path:     /admin/deleted
    defaults: { _controller: 'Admin', _action: 'wipe' }

api_leagueoverseer:
    path:     /api/leagueOverseer
    defaults: { _controller: 'LeagueOverseerHook', _action: 'query' }

ban_list:
    path:     /bans
    defaults: { _controller: 'Ban', _action: 'list' }

ban_create:
    path:     /bans/new
    defaults: { _controller: 'Ban', _action: 'create' }

ban_create_player:
    path:     /bans/new/{player}
    defaults: { _controller: 'Ban', _action: 'create' }

ban_show:
    path:     /bans/{ban}
    defaults: { _controller: 'Ban', _action: 'show' }

ban_edit:
    path:     /bans/{ban}/edit
    defaults: { _controller: 'Ban', _action: 'edit' }

ban_expire:
    path:     /bans/{ban}/unban
    defaults: { _controller: 'Ban', _action: 'unban' }

ban_delete:
    path:     /bans/{ban}/delete
    defaults: { _controller: 'Ban', _action: 'delete' }

invitation_accept:
    path:     /invitations/{invitation}
    defaults: { _controller: 'Invitation', _action: 'accept' }

login:
    path:     /login
    defaults: { _controller: 'Login', _action: 'login', _noMaint: true }

logout:
    path:     /logout
    defaults: { _controller: 'Login', _action: 'logout', _noMaint: true }

map_list:
    path:     /maps/
    defaults: { _controller: 'Map', _action: 'list' }

map_add:
    path:     /maps/new
    defaults: { _controller: 'Map', _action: 'create' }

map_show:
    path:     /maps/{map}
    defaults: { _controller: 'Map', _action: 'list' }

map_edit:
    path:     /maps/{map}/edit
    defaults: { _controller: 'Map', _action: 'edit' }

map_delete:
    path:     /maps/{map}/delete
    defaults: { _controller: 'Map', _action: 'delete' }

match_list:
    path:     /matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list:
    path:     /teams/{team}/matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list_sort:
    path:     /teams/{team}/matches/{type}
    defaults: { _controller: 'Match', _action: 'list' }

match_enter:
    path:     /matches/enter
    defaults: { _controller: 'Match', _action: 'create' }

match_edit:
    path:     /matches/{match}/edit
    defaults: { _controller: 'Match', _action: 'edit' }

match_delete:
    path:     /matches/{match}/delete
    defaults: { _controller: 'Match', _action: 'delete' }

match_recalculate:
    path:     /matches/{match}/recalculate
    defaults: { _controller: 'Match', _action: 'recalculate' }

message_list:
    path:     /messages
    defaults: { _controller: 'Message', _action: 'list' }

message_compose:
    path:     /messages/compose
    defaults: { _controller: 'Message', _action: 'compose' }

message_search:
    path:     /messages/search
    defaults: { _controller: 'Message', _action: 'search' }

message_conversation_show:
    path:     /messages/{conversation}
    defaults: { _controller: 'Message', _action: 'show' }

message_conversation_leave:
    path:     /messages/{conversation}/leave
    defaults: { _controller: 'Message', _action: 'leave' }

message_conversation_team_leave:
    path:     /messages/{conversation}/team-leave
    defaults: { _controller: 'Message', _action: 'teamLeave' }

message_conversation_kick:
    path:     /messages/{conversation}/kick/{type}/{member}
    defaults: { _controller: 'Message', _action: 'kick' }

news_list:
    path:     /news
    defaults: { _controller: 'News', _action: 'list' }

news_new:
    path:     /news/new
    defaults: { _controller: 'News', _action: 'create' }

news_show:
    path:     /news/{article}
    defaults: { _controller: 'News', _action: 'show' }

news_edit:
    path:     /news/{article}/edit
    defaults: { _controller: 'News', _action: 'edit' }

news_delete:
    path:     /news/{article}/delete
    defaults: { _controller: 'News', _action: 'delete' }

news_category_show:
    path:     /news/category/{category}
    defaults: { _controller: 'News', _action: 'list' }

notification_list:
    path:     /notifications
    defaults: { _controller: 'Notification', _action: 'list' }

player_list:
    path:     /players
    defaults: { _controller: 'Player', _action: 'list' }

player_show:
    path:     /players/{player}
    defaults: { _controller: 'Player', _action: 'show' }

player_edit:
    path:     /players/{player}/edit
    defaults: { _controller: 'Player', _action: 'edit' }

profile_show:
    path:     /profile
    defaults: { _controller: 'Profile', _action: 'show' }

profile_edit:
    path:     /profile/edit
    defaults: { _controller: 'Profile', _action: 'edit' }

profile_confirm:
    path:     /profile/confirm/{token}
    defaults: { _controller: 'Profile', _action: 'confirm' }

search:
    path:    /search
    defaults: { _controller: 'Search', _action: 'search' }

server_list:
    path:     /servers
    defaults: { _controller: 'Server', _action: 'list' }

server_new:
    path:     /servers/new
    defaults: { _controller: 'Server', _action: 'create' }

server_show:
    path:     /servers/{server}
    defaults: { _controller: 'Server', _action: 'show' }

server_delete:
    path:     /servers/{server}/delete
    defaults: { _controller: 'Server', _action: 'delete' }

server_edit:
    path:     /servers/{server}/edit
    defaults: { _controller: 'Server', _action: 'edit' }

team_list:
    path:     /teams
    defaults: { _controller: 'Team', _action: 'list' }

team_new:
    path:     /teams/new
    defaults: { _controller: 'Team', _action: 'create' }

team_show:
    path:     /teams/{team}
    defaults: { _controller: 'Team', _action: 'show' }

team_members:
    path:     /teams/{team}/members
    defaults: { _controller: 'Player', _action: 'list' }

team_join:
    path:     /teams/{team}/join
    defaults: { _controller: 'Team', _action: 'join' }

team_edit:
    path:     /teams/{team}/edit
    defaults: { _controller: 'Team', _action: 'edit' }

team_delete:
    path:     /teams/{team}/delete
    defaults: { _controller: 'Team', _action: 'delete' }

team_kick:
    path:     /teams/{team}/kick/{player}
    defaults: { _controller: 'Team', _action: 'kick' }

team_invite:
    path:     /teams/{team}/invite/{player}
    defaults: { _controller: 'Invitation', _action: 'invite' }

team_assign_leader:
    path:     /teams/{team}/change-leader/{player}
    defaults: { _controller: 'Team', _action: 'assignLeader' }

team_abandon:
    path:     /teams/{team}/abandon
    defaults: { _controller: 'Team', _action: 'abandon' }

custom_page_create:
    path:     /pages/new
    defaults: { _controller: 'Page', _action: 'create' }

custom_page_show:
    path:     /{page}
    defaults: { _controller: 'Page', _action: 'show' }

custom_page_edit:
    path:     /{page}/edit
    defaults: { _controller: 'Page', _action: 'edit' }

custom_page_delete:
    path:     /{page}/delete
    defaults: { _controller: 'Page', _action: 'delete' }

# FIXME: Disabled temporarily, since it contains deprecated code that makes tests fail
# NelmioApiDocBundle:
#     resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#     prefix:   /api/doc
#     defaults: { _defaultHandler: true }

trailing_slash:
    path:  /{url}
    defaults: { _controller: 'Redirecting', _action: 'removeTrailingSlash' }
    methods: [GET]
    requirements:
        url: .*/$
